# Generated by Django 4.0.6 on 2022-07-19 22:44

import base.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_object', models.ImageField(upload_to=base.models.upload_to)),
            ],
        ),
    ]
